### ISSUE TITLE
Softkey transparency

### ISSUE THREAD

**Issue by aminota** [DUBULEE/Android-LockScreenSample-DisableHomeButtonKey#1]
Hello @DUBULEE ! 
Thanks for starting this project ! 

As we see in your examples of the LG G and Google Nexus,  do you know why the background of the others activities appears behind the virtual keys bar ? Can we do something about this or it's a virtual key mobile limitation ? did you try something like fullscreen or force black background of the softkeys ?
What are the differents option did you try to avoid this transparency? (to avoid spend time to retest them ..)

Regards,
Alex

**Comment by DUBULEE** [comment]
Hello @aminota 
Thanks for your qeustion.

I write my thoughts... 

Q1. As we see in your examples of the LG G and Google Nexus, 
do you know why the background of the others activities appears behind the virtual keys bar ? 

[Answer 1]
I think... this is a bug... 
but I didn't show this present situation.
Please, More detail ... (ex: Reproduction path)
I'll find a way to modify.
Or.. Best is .. If you modify that, Send PR.  :)

Also, You can see How to Control navigation Bar ..  
this link (http://developer.android.com/intl/ko/training/system-ui/navigation.html) 

Q2. Can we do something about this or it's a virtual key mobile limitation ?

[Answer 2]
Um...  There is some restriction... 
You can see in other similar lock screen App. 
   - Microsoft Corp -  Next Lock  <--- eliminates soft key... 
   - Kakao Corp. - Notification Cover in  Kakao Talk   <-- has same problem..


Q3. did you try something like fullscreen or force black background of the softkeys ?

[Answer 3]

No. I didn't try... but  You can see How to Control navigation Bar ..  
this link (http://developer.android.com/intl/ko/training/system-ui/navigation.html) 

Q4. What are the differents option did you try to avoid this transparency? (to avoid spend time to retest them ..)

[Answer 4]
I'll find a way to modify. But...perhaps it will be difficult.
Because this lib use service process.
Please Let me know if yo find a way.

You can see same problem in Kakao Corp. - Notification Cover in  Kakao Talk 
So... sad... 

Anyway.. I am sorry I could not help it.

If you want to contact  me, send mail.
my mail: dubudev@dubulee.com

Thanks~ Alex! 

Regards,
DUBU LEE
